server:
  port: 8093
spring:
  data:
    mongodb:
      uri: mongodb+srv://sovathc:vE4DChedB5sJs5NO@cluster0.y598ufq.mongodb.net/mongodb-spring-crud?retryWrites=true&w=majority
  jackson:
      property-naming-strategy: SNAKE_CASE
